services:
  db:
    container_name: 'opportunities-db'
    image: postgres
    volumes:
      - './database/postgres-data:/var/lib/postgresql/data:rw'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
